Repository Shaixyz/Landing-Page, pull requests merged in 2024-09, with the labels that each got.

#8 Test noti
  package-lock.json
  package.json
  src/Notification/Notification.js
  src/assets/R.png
  src/assets/icon.ico
  src/components/Layout/components/Header/index.js
  src/components/auth/AuthRoute.js
  src/pages/Admin/Dashboardview.js
  src/pages/Admin/Sidebar.js
  src/pages/Home/index.js
Labels: documentation, enhancement, good first issue

#9 Noti
  package-lock.json
  package.json
  src/Notification/Notification.js
  src/assets/R.png
  src/assets/icon.ico
  src/components/Layout/components/Header/index.js
  src/components/auth/AuthRoute.js
  src/pages/Admin/Dashboardview.js
  src/pages/Admin/Sidebar.js
  src/pages/Home/index.js
Labels: enhancement

#10 New Feature
  package-lock.json
  package.json
  src/App.js
  src/assets/detailproduct/image-product-1-thumbnail.jpg
  src/assets/detailproduct/image-product-1.jpg
  src/assets/detailproduct/image-product-2-thumbnail.jpg
  src/assets/detailproduct/image-product-2.jpg
  src/assets/detailproduct/image-product-3-thumbnail.jpg
  src/assets/detailproduct/image-product-3.jpg
  src/assets/detailproduct/image-product-4-thumbnail.jpg
  src/assets/detailproduct/image-product-4.jpg
  src/assets/icon-cart-white.svg
  src/assets/icon-cart.svg
  src/assets/icon-close-white.svg
  src/assets/icon-close.svg
  src/assets/icon-next.svg
  src/assets/icon-previous.svg
  src/components/Layout/components/Header/index.js
  src/context/auth/AuthContext.js
  src/context/slices/authSlice.js
  src/context/slices/store.js
  src/index.js
  src/pages/DetailProduct/DetailProductPage.js
  src/pages/Notification/ChatLayout.js
  src/pages/Notification/Sidebar.js
  src/pages/Search/Data.js
  src/pages/Search/SearchPage.js
  src/pages/Seller/CreateGadget.js
  src/pages/Seller/Data.js
  src/pages/Seller/Header.js
  tailwind.config.js
Labels: enhancement

#12 quay xexe
  src/context/auth/AuthContext.js
Labels: bug
